import "./globals.css";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={'bodyFont'}>
          <div className="min-h-screen flex flex-col p-3 md:px-12 md:pt-4 gap-4 md:gap-24">
            <Header/>
            {children}
            <Footer/>
          </div>
      </body>
    </html>
);
}
